name: Check and Rebuild Tempest Image

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to run checks on and re-build images from
        type: string
        required: true

jobs:
  check-update:
    runs-on: ubuntu-latest
    outputs:
      rebuild_image: ${{ steps.check.outputs.rebuild_image }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Install yq
        run: |
          sudo snap install yq
      - name: Check if a recent snap updates is found
        id: check
        run: |
          # get the snap name and its channel that the ROCK image should track
          snap=$(yq '.parts.[].stage-snaps.[]' rocks/tempest/rockcraft.yaml)
          IFS='/' read -r name channel <<< "$snap"
          echo "snap: $name, channel: $channel"

          # parse date of the last release and reformat it to seconds
          format='+%s'
          last_release_date=$(snap info tempest | grep "2023.2/stable" | awk '{ print $3 }')
          echo "last release date in channel $channel: $last_release_date"
          last_release_date_in_seconds=$(date -d "$last_release_date" "$format")

          # confirm the validity of the release date
          if [[ $? != 0 ]]; then
            echo "$last_release_date is not a valid date."
          fi

          # get current date and reformat it to seconds
          cur_date=$(date)
          echo "current date: $cur_date"
          cur_date_in_seconds=$(date -d "$cur_date" "$format")

          # get the date difference between two days
          date_diff=$(( ($cur_date_in_seconds - $last_release_date_in_seconds)/(60*60*24) ))
          
          # re-build image if the date difference is less than or equal to 5 days
          if [ $date_diff -le 5 ]; then
              echo "A recent snap release is found. Will re-build a new image."
              echo "rebuild_image=1" >> $GITHUB_OUTPUT
          else
              echo "No new snap releases detected."
              echo "rebuild_image=0" >> $GITHUB_OUTPUT
          fi

  build-and-publish:
    needs: check-update
    if: ${{ needs.check-update.outputs.rebuild_image == 1 }}
    uses: ./.github/workflows/build_publish.yaml
    with:
      rocks: '["tempest"]'
      branch: ${{ inputs.branch }}
      publish: true
