name: Update Tempest Releases
on:
  workflow_dispatch:
  schedule:
    - cron: '12 1 * * 2,5' # run workflow at 1:12 (an arbitrary time) every Tue and Fri 

jobs:
  check-update:
    strategy:
      fail-fast: false
      matrix:
        branch: ["main", "stable/2023.1"]
    uses: ./.github/workflows/check_rebuild_tempest.yaml
    with:
      openstack-release: ${{ matrix.branch }}
